<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\Author;

use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {

        $books = [
            [
                'ISBN' => '9786163371140',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/157947/Thumbnail/book_detail_large.gif?2',
                'price' => 171,
                'pages_num' => 449,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2015-10-1 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163371539',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/157948/Thumbnail/book_detail_large.gif?2',
                'price' => 198,
                'pages_num' => 449,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2015-10-1 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163372079',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/157949/Thumbnail/book_detail_large.gif?2',
                'price' => 198,
                'pages_num' => 438,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2015-12-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163372888',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/157950/Thumbnail/book_detail_large.gif?2',
                'price' => 198,
                'pages_num' => 441,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2016-07-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163373229',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/157951/Thumbnail/book_detail_large.gif?2',
                'price' => 198,
                'pages_num' => 409,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2016-12-07 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163373601',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/158862/Thumbnail/book_detail_large.gif?2',
                'price' => 198,
                'pages_num' => 409,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2017-5-20 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163374059',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/158863/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 397,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2017-09-09 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163374929',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/158864/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 413,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2018-05-14 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163375056',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/158866/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 446,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2018-8-11 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163376183',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/158867/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 429,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2019-10-19 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163376855',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 11',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/160792/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 461,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2020-7-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163377531',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 12',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/160793/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 457,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2021-05-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163377722',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 13',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/175129/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 429,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2021-12-03 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163378088',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 14',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/184356/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 432,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2022-02-07 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163378569',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 15',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/196197/Thumbnail/book_detail_large.gif?2',
                'price' => 216,
                'pages_num' => 453,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2022-05-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163376602',
                'name' => 'Re:Zero - Restarting Life from Zero in Another World Volume 16',
                'cover' => 'https://fs.lnwfile.com/_/fs/_raw/pr/6j/nj.jpg',
                'price' => 216,
                'pages_num' => 432,
                'publisher_name' => 'A Plus',
                'publisher_date' => '2022-08-24 00:00:00',
                'description' => 'description text',
                'author_name' => 'Nagatsuki Tappei',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164474093',
                'name' => 'Fly Me to The Moon Volume 1',
                'cover' => 'https://cdn1.mangaqube.com/O47BADSHBM9JDA58_l',
                'price' => 80,
                'pages_num' => 198,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2019-03-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164475892',
                'name' => 'Fly Me to The Moon Volume 2',
                'cover' => 'https://cdn1.mangaqube.com/KFAOU330EJ61FP70_l',
                'price' => 80,
                'pages_num' => 200,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2019-08-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164477100',
                'name' => 'Fly Me to The Moon Volume 3',
                'cover' => 'https://cdn1.mangaqube.com/NXENQCDPC8WP658Q_l',
                'price' => 80,
                'pages_num' => 200,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2019-10-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164478305',
                'name' => 'Fly Me to The Moon Volume 4',
                'cover' => 'https://cdn1.mangaqube.com/60ZSET5ZVKBIGNL6_l',
                'price' => 80,
                'pages_num' => 196,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2020-04-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '0',
                'name' => 'Fly Me to The Moon Volume 5',
                'cover' => 'https://cdn1.mangaqube.com/yaXGGoWRrPkKmGrM_l',
                'price' => 80,
                'pages_num' => 196,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2021-03-10 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164473091',
                'name' => 'Fly Me to The Moon Volume 6',
                'cover' => 'https://cdn1.mangaqube.com/2ZTg7cmgDKbUqzop_l',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2021-04-21 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164474596',
                'name' => 'Fly Me to The Moon Volume 7',
                'cover' => 'https://cdn1.mangaqube.com/2dEihr20QwQTiwmb_l',
                'price' => 80,
                'pages_num' => 200,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2021-07-19 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786165744461',
                'name' => 'Fly Me to The Moon Volume 8',
                'cover' => 'https://cdn1.mangaqube.com/fiUWQoW9gHtAKw9N_l',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => 'LuckPim',
                'publisher_date' => '2022-04-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kenjiro Hata',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786168105443',
                'name' => 'Welcome to the Classroom of the Elite Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/95067/Thumbnail/book_detail_large.gif?11',
                'price' => 247,
                'pages_num' => 347,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2017-10-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786168105764',
                'name' => 'Welcome to the Classroom of the Elite Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/95068/Thumbnail/book_detail_large.gif?11',
                'price' => 243,
                'pages_num' => 330,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2018-3-20 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164640337',
                'name' => 'Welcome to the Classroom of the Elite Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/95069/Thumbnail/book_detail_large.gif?11',
                'price' => 277,
                'pages_num' => 356,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2018-07-20 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164640696',
                'name' => 'Welcome to the Classroom of the Elite Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/95072/Thumbnail/book_detail_large.gif?14',
                'price' => 293,
                'pages_num' => 364,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2018-10-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164641068',
                'name' => 'Welcome to the Classroom of the Elite Volume 4.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/95074/Thumbnail/book_detail_large.gif?12',
                'price' => 275,
                'pages_num' => 332,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2019-01-12 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164641525',
                'name' => 'Welcome to the Classroom of the Elite Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/95076/Thumbnail/book_detail_large.gif?12',
                'price' => 284,
                'pages_num' => 347,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2019-04-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164641686',
                'name' => 'Welcome to the Classroom of the Elite Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/97068/Thumbnail/book_detail_large.gif?10',
                'price' => 228,
                'pages_num' => 340,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2019-06-18 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164641983',
                'name' => 'Welcome to the Classroom of the Elite Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/104880/Thumbnail/book_detail_large.gif?2',
                'price' => 279,
                'pages_num' => 326,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2019-10-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164642867',
                'name' => 'Welcome to the Classroom of the Elite Volume 7.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/116093/Thumbnail/book_detail_large.gif?5',
                'price' => 266,
                'pages_num' => 312,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2020-04-01 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164643116',
                'name' => 'Welcome to the Classroom of the Elite Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/118456/Thumbnail/book_detail_large.gif?2',
                'price' => 275,
                'pages_num' => 260,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2020-04-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164643512',
                'name' => 'Welcome to the Classroom of the Elite Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/126575/Thumbnail/book_detail_large.gif?2',
                'price' => 248,
                'pages_num' => 320,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2020-07-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164643789',
                'name' => 'Welcome to the Classroom of the Elite Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/131941/Thumbnail/book_detail_large.gif?2',
                'price' => 275,
                'pages_num' => 320,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2020-10-02 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164644274',
                'name' => 'Welcome to the Classroom of the Elite Volume 11',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/139838/Thumbnail/book_detail_large.gif?4',
                'price' => 284,
                'pages_num' => 340,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2021-01-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164644786',
                'name' => 'Welcome to the Classroom of the Elite Volume 11.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/148639/Thumbnail/book_detail_large.gif?2',
                'price' => 284,
                'pages_num' => 336,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2021-04-21 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kinugasa Syougo',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163375391',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169958/Thumbnail/book_detail_large.gif?2',
                'price' => 288,
                'pages_num' => 374,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2018-11-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163375681',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169959/Thumbnail/book_detail_large.gif?6',
                'price' => 288,
                'pages_num' => 358,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2019-04-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163376367',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169960/Thumbnail/book_detail_large.gif?2',
                'price' => 288,
                'pages_num' => 365,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2019-10-26 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163376558',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169962/Thumbnail/book_detail_large.gif?2',
                'price' => 288,
                'pages_num' => 359,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2020-04-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163377081',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169963/Thumbnail/book_detail_large.gif?2',
                'price' => 288,
                'pages_num' => 367,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2020-11-02 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163377425',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169964/Thumbnail/book_detail_large.gif?5',
                'price' => 288,
                'pages_num' => 355,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2021-05-15 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163378019',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/175108/Thumbnail/book_detail_large.gif?2',
                'price' => 288,
                'pages_num' => 365,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2021-12-11 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163378118',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/184357/Thumbnail/book_detail_large.gif?4',
                'price' => 315,
                'pages_num' => 366,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2022-02-07 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163378613',
                'name' => 'How a Realist Hero Rebuilt The Kingdom Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/204905/Thumbnail/book_detail_large.gif?2',
                'price' => 315,
                'pages_num' => 367,
                'publisher_name' => ' A Plus',
                'publisher_date' => '2022-07-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Dojyomaru',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165743563',
                'name' => 'My Dress-Up Darling Volume 1',
                'cover' => 'http://prodimage.images-bn.com/pimages/9781646090327_p0_v2_s1200x630.jpg',
                'price' => 80,
                'pages_num' => 208,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2019-10-02 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786165742498',
                'name' => 'My Dress-Up Darling Volume 2',
                'cover' => 'https://prodimage.images-bn.com/pimages/9781646090334_p0_v2_s600x595.jpg',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2019-10-02 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164476929',
                'name' => 'My Dress-Up Darling Volume 3',
                'cover' => 'https://prodimage.images-bn.com/pimages/9781646090341_p0_v2_s600x595.jpg',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2019-12-23 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164479005',
                'name' => 'My Dress-Up Darling Volume 4',
                'cover' => 'https://prodimage.images-bn.com/pimages/9781646090518_p0_v91_s600x595.jpg',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2020-06-26 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164476554',
                'name' => 'My Dress-Up Darling Volume 5',
                'cover' => 'https://prodimage.images-bn.com/pimages/9781646091133_p0_v2_s600x595.jpg',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2021-07-28 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164476561',
                'name' => 'My Dress-Up Darling Volume 6',
                'cover' => 'http://prodimage.images-bn.com/pimages/9781646091287_p0_v2_s1200x630.jpg',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2021-11-10 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786164476568',
                'name' => 'My Dress-Up Darling Volume 7',
                'cover' => 'https://prodimage.images-bn.com/pimages/9781646091645_p0_v1_s600x595.jpg',
                'price' => 80,
                'pages_num' => 192,
                'publisher_name' => ' LuckPim',
                'publisher_date' => '2022-02-18 00:00:00',
                'description' => 'description text',
                'author_name' => 'Shinichi Fukuda',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786167932040',
                'name' => 'The Rising of the Shield Hero Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146805/Thumbnail/book_detail_large.gif?2',
                'price' => 225,
                'pages_num' => 380,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2015-03-17 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932057',
                'name' => 'The Rising of the Shield Hero Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146806/Thumbnail/book_detail_large.gif?3',
                'price' => 243,
                'pages_num' => 380,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2015-05-12 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932095',
                'name' => 'The Rising of the Shield Hero Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146807/Thumbnail/book_detail_large.gif?2',
                'price' => 243,
                'pages_num' => 396,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2015-11-06 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932125',
                'name' => 'The Rising of the Shield Hero Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146808/Thumbnail/book_detail_large.gif?3',
                'price' => 252,
                'pages_num' => 398,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2016-04-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932170',
                'name' => 'The Rising of the Shield Hero Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146809/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 410,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2016-08-13 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932248',
                'name' => 'The Rising of the Shield Hero Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146810/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 414,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2016-10-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932293',
                'name' => 'The Rising of the Shield Hero Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146811/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 402,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2017-04-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932392',
                'name' => 'The Rising of the Shield Hero Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146812/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 410,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2017-10-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932460',
                'name' => 'The Rising of the Shield Hero Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146813/Thumbnail/book_detail_large.gif?2',
                'price' => 279,
                'pages_num' => 420,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2018-01-17 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932835',
                'name' => 'The Rising of the Shield Hero Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146814/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 412,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2018-11-26 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890046',
                'name' => 'The Rising of the Shield Hero Volume 11',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146815/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 408,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2019-05-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890237',
                'name' => 'The Rising of the Shield Hero Volume 12',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146816/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 400,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2019-09-11 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890404',
                'name' => 'The Rising of the Shield Hero Volume 13',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/146817/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 374,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2019-11-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890405',
                'name' => 'The Rising of the Shield Hero Volume 14',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/155858/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 392,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2021-06-11 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164891517',
                'name' => 'The Rising of the Shield Hero Volume 15',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/181799/Thumbnail/book_detail_large.gif?2',
                'price' => 288,
                'pages_num' => 394,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2022-02-11 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164891777',
                'name' => 'The Rising of the Shield Hero Volume 16',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/200045/Thumbnail/book_detail_large.gif?5',
                'price' => 288,
                'pages_num' => 400,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2022-07-01 00:00:00',
                'description' => 'description text',
                'author_name' => 'Aneko Yusagi',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164646193',
                'name' => 'Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/174544/Thumbnail/book_detail_large.gif?7',
                'price' => 261,
                'pages_num' => 248,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2021-12-03 00:00:00',
                'description' => 'description text',
                'author_name' => 'sun sun sun',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164646681',
                'name' => 'Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/184347/Thumbnail/book_detail_large.gif?2',
                'price' => 266,
                'pages_num' => 276,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2022-03-04 00:00:00',
                'description' => 'description text',
                'author_name' => 'sun sun sun',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164647831',
                'name' => 'Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/200646/Thumbnail/book_detail_large.gif?2',
                'price' => 275,
                'pages_num' => 340,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2022-08-02 00:00:00',
                'description' => 'description text',
                'author_name' => 'sun sun sun',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164648675',
                'name' => 'Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/208922/Thumbnail/book_detail_large.gif?4',
                'price' => 269,
                'pages_num' => 320,
                'publisher_name' => ' Phoenix',
                'publisher_date' => '2022-09-13 00:00:00',
                'description' => 'description text',
                'author_name' => 'sun sun sun',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932088',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133847/Thumbnail/book_detail_large.gif?2',
                'price' => 243,
                'pages_num' => 318,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2015-11-09 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932101',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133848/Thumbnail/book_detail_large.gif?2',
                'price' => 243,
                'pages_num' => 330,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2015-11-09 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932132',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133849/Thumbnail/book_detail_large.gif?2',
                'price' => 243,
                'pages_num' => 270,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2016-04-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932231',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133850/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 392,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2016-10-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932347',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133851/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 410,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2017-08-15 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932583',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133852/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 391,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2018-07-10 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786167932965',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133853/Thumbnail/book_detail_large.gif?3',
                'price' => 270,
                'pages_num' => 390,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2019-05-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890053',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133854/Thumbnail/book_detail_large.gif?2',
                'price' => 270,
                'pages_num' => 400,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2019-06-18 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890350',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133855/Thumbnail/book_detail_large.gif?7',
                'price' => 315,
                'pages_num' => 486,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2019-10-24 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164890978',
                'name' => 'Death Marching to the Parallel World Rhapsody Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/141571/Thumbnail/book_detail_large.gif?2',
                'price' => 315,
                'pages_num' => 456,
                'publisher_name' => ' First Page Pro',
                'publisher_date' => '2021-01-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Hiro Ainana',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163631237',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92885/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 296,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2015-12-03 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163632098',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92886/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 296,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2016-04-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163632432',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92887/Thumbnail/book_detail_large.gif?6',
                'price' => 251,
                'pages_num' => 324,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2016-08-05 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163633057',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92888/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 300,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2017-01-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163633552',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92889/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 300,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2017-10-24 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163633965',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92890/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 321,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2018-03-23 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163634405',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92891/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 308,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2018-06-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163635037',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92892/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 308,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2019-01-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163635471',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/99966/Thumbnail/book_detail_large.gif?3',
                'price' => 251,
                'pages_num' => 332,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2019-07-31 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163635860',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/114673/Thumbnail/book_detail_large.gif?2',
                'price' => 251,
                'pages_num' => 308,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2020-02-28 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163636362',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 11',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133411/Thumbnail/book_detail_large.gif?2',
                'price' => 251,
                'pages_num' => 316,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2020-10-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163636485',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 12',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/140307/Thumbnail/book_detail_large.gif?2',
                'price' => 251,
                'pages_num' => 300,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2020-12-10 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163637062',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 13',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/152428/Thumbnail/book_detail_large.gif?2',
                'price' => 251,
                'pages_num' => 308,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2021-04-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165830928',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 14',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/173326/Thumbnail/book_detail_large.gif?2',
                'price' => 251,
                'pages_num' => 308,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2021-11-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165831529',
                'name' => 'Jobless Reincarnation - It Will be All Out if I Go to Another World Volume 15',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/191050/Thumbnail/book_detail_large.gif?5',
                'price' => 251,
                'pages_num' => 324,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2022-04-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Rifujin na Magonote',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163632128',
                'name' => 'Overlord Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92883/Thumbnail/book_detail_large.gif?4',
                'price' => 269,
                'pages_num' => 374,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2016-04-29 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786164132320',
                'name' => 'Overlord Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92508/Thumbnail/book_detail_large.gif?6',
                'price' => 269,
                'pages_num' => 362,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2016-10-15 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163633262',
                'name' => 'Overlord Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92509/Thumbnail/book_detail_large.gif?4',
                'price' => 269,
                'pages_num' => 414,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2017-04-20 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786169292722',
                'name' => 'Overlord Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92510/Thumbnail/book_detail_large.gif?4',
                'price' => 269,
                'pages_num' => 416,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2017-11-03 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163634115',
                'name' => 'Overlord Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92511/Thumbnail/book_detail_large.gif?4',
                'price' => 269,
                'pages_num' => 372,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2018-04-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163634580',
                'name' => 'Overlord Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92512/Thumbnail/book_detail_large.gif?4',
                'price' => 287,
                'pages_num' => 436,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2018-10-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163635310',
                'name' => 'Overlord Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/92884/Thumbnail/book_detail_large.gif?4',
                'price' => 287,
                'pages_num' => 362,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2019-04-09 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163635686',
                'name' => 'Overlord Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/105538/Thumbnail/book_detail_large.gif?2',
                'price' => 287,
                'pages_num' => 408,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2019-12-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163635952',
                'name' => 'Overlord Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/116634/Thumbnail/book_detail_large.gif?2',
                'price' => 287,
                'pages_num' => 438,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2020-03-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163636348',
                'name' => 'Overlord Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/133413/Thumbnail/book_detail_large.gif?2',
                'price' => 287,
                'pages_num' => 456,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2020-10-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163636928',
                'name' => 'Overlord Volume 11',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/152429/Thumbnail/book_detail_large.gif?2',
                'price' => 287,
                'pages_num' => 462,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2021-04-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165830805',
                'name' => 'Overlord Volume 12',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/169983/Thumbnail/book_detail_large.gif?2',
                'price' => 287,
                'pages_num' => 402,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2021-10-04 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165831697',
                'name' => 'Overlord Volume 13',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/191051/Thumbnail/book_detail_large.gif?5',
                'price' => 287,
                'pages_num' => 564,
                'publisher_name' => ' Dream EXpress',
                'publisher_date' => '2022-04-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Kugane Maruyama',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163241887',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125918/Thumbnail/book_detail_large.gif?2',
                'price' => 128,
                'pages_num' => 359,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2018-07-18 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163242457',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125919/Thumbnail/book_detail_large.gif?2',
                'price' => 116,
                'pages_num' => 296,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2015-01-20 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163243577',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125920/Thumbnail/book_detail_large.gif?2',
                'price' => 128,
                'pages_num' => 351,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2015-11-19 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163244215',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 4',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125922/Thumbnail/book_detail_large.gif?2',
                'price' => 128,
                'pages_num' => 314,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2016-05-05 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163244826',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125928/Thumbnail/book_detail_large.gif?3',
                'price' => 116,
                'pages_num' => 239,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2016-10-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163245502',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 6',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125931/Thumbnail/book_detail_large.gif?2',
                'price' => 144,
                'pages_num' => 376,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2017-05-17 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165610087',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 6.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125932/Thumbnail/book_detail_large.gif?2',
                'price' => 192,
                'pages_num' => 519,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2019-10-24 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163246561',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 7',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125933/Thumbnail/book_detail_large.gif?2',
                'price' => 144,
                'pages_num' => 374,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2017-11-07 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163247353',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 7.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125935/Thumbnail/book_detail_large.gif?2',
                'price' => 136,
                'pages_num' => 296,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2018-04-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163248435',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 8',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125937/Thumbnail/book_detail_large.gif?2',
                'price' => 160,
                'pages_num' => 391,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2018-11-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163249067',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 9',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/125939/Thumbnail/book_detail_large.gif?2',
                'price' => 176,
                'pages_num' => 479,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2019-05-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165610698',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 10',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/126644/Thumbnail/book_detail_large.gif?3',
                'price' => 192,
                'pages_num' => 375,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2020-05-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165611350',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 10.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/135748/Thumbnail/book_detail_large.gif?2',
                'price' => 144,
                'pages_num' => 247,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2020-10-21 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165611527',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 11',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/141737/Thumbnail/book_detail_large.gif?2',
                'price' => 176,
                'pages_num' => 326,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2020-12-23 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165611985',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 12',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/152665/Thumbnail/book_detail_large.gif?2',
                'price' => 192,
                'pages_num' => 391,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-04-23 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165612203',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 13',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/164973/Thumbnail/book_detail_large.gif?2',
                'price' => 192,
                'pages_num' => 383,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-08-11 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165612623',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 14',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/174316/Thumbnail/book_detail_large.gif?2',
                'price' => 240,
                'pages_num' => 551,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-11-10 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165612777',
                'name' => 'My Youth Romantic Comedy Is Wrong as I Expected Volume 14.5',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/182039/Thumbnail/book_detail_large.gif?2',
                'price' => 144,
                'pages_num' => 224,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2022-01-20 00:00:00',
                'description' => 'description text',
                'author_name' => 'Wataru WATARI',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163241894',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 1',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/2/26/Light_Novel_Volume_1.jpg',
                'price' => 144,
                'pages_num' => 224,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2014-07-18 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163242433',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 2',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/9/96/DanMachi_Light_Novel_Volume_2_Cover.jpg/revision/latest?cb=20210415083104',
                'price' => 153,
                'pages_num' => 256,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2015-01-13 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163242594',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 3',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/3/37/DanMachi_Light_Novel_Volume_3_Cover.png/revision/latest/scale-to-width-down/350?cb=20150605081216',
                'price' => 131,
                'pages_num' => 208,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2015-05-07 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163243430',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 4',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/5/5a/DanMachi_Light_Novel_Volume_4_Cover.png/revision/latest/scale-to-width-down/348?cb=20150605081246',
                'price' => 144,
                'pages_num' => 240,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2015-11-13 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163244116',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 5',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/3/3e/DanMachi_Light_Novel_Volume_5_Cover.jpg/revision/latest/scale-to-width-down/350?cb=20210415092119',
                'price' => 162,
                'pages_num' => 288,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2016-04-27 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163244871',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 6',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/1/1a/DanMachi_Light_Novel_Volume_6_Cover.png/revision/latest/scale-to-width-down/349?cb=20150605081311',
                'price' => 153,
                'pages_num' => 272,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2016-11-16 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163245281',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 7',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/e/ea/DanMachi_Light_Novel_Volume_7_Cover.png/revision/latest/scale-to-width-down/350?cb=20150605081700',
                'price' => 189,
                'pages_num' => 384,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2017-04-26 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163246707',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 8',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/b/b6/DanMachi_Light_Novel_Volume_8_Cover.png/revision/latest/scale-to-width-down/350?cb=20150605081723',
                'price' => 189,
                'pages_num' => 400,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2017-11-30 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163246950',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 9',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/2/2e/DanMachi_Light_Novel_Volume_9.jpg/revision/latest/scale-to-width-down/350?cb=20210417092750',
                'price' => 162,
                'pages_num' => 276,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2018-01-25 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163247414',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 10',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/5/59/DanMachi_Light_Novel_Volume_10_Cover.png/revision/latest/scale-to-width-down/349?cb=20160421211603',
                'price' => 180,
                'pages_num' => 299,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2018-04-19 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163248190',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 11',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/6/6a/DanMachi_Light_Novel_Volume_11_Cover.png/revision/latest/scale-to-width-down/350?cb=20160920185412',
                'price' => 198,
                'pages_num' => 316,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2018-11-22 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163249135',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 12',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/2/27/Volume_12_Cover.jpg/revision/latest/scale-to-width-down/350?cb=20170521012224',
                'price' => 180,
                'pages_num' => 249,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2019-04-24 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786163249982',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 13',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/4/48/DanMachi_Light_Novel_Volume_13_Cover.png/revision/latest?cb=20180125131224',
                'price' => 180,
                'pages_num' => 217,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2019-11-06 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165611008',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 14',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/a/ae/DanMachi_Light_Novel_Volume_14.jpg/revision/latest/scale-to-width-down/350?cb=20210416192144',
                'price' => 306,
                'pages_num' => 424,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2020-07-08 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165611220',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 15',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/2/27/Volume_15_Cover.jpg/revision/latest/scale-to-width-down/350?cb=20190524095821',
                'price' => 216,
                'pages_num' => 244,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2020-11-04 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165612609',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 16',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/2/2c/Volume_16_Cover.jpg/revision/latest/scale-to-width-down/350?cb=20200915142449',
                'price' => 216,
                'pages_num' => 264,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-11-24 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165613224',
                'name' => 'Is It Wrong To Try To Pick Up Girls In A Dungeon? Volume 17',
                'cover' => 'https://static.wikia.nocookie.net/dungeon-ni-deai-o-motomeru/images/a/af/Volume_17_Cover.jpg/revision/latest/scale-to-width-down/350?cb=20210422080500',
                'price' => 270,
                'pages_num' => 316,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2022-05-12 00:00:00',
                'description' => 'description text',
                'author_name' => 'Fujino Omori',
                'stock' => 100,
                'manga_flag' => false,
                'novel_flag' => true
            ],
            [
                'ISBN' => '9786165611909',
                'name' => 'Miss Kobayashi Dragon Maid Volume 1',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/152668/Thumbnail/book_detail_large.gif?2',
                'price' => 81,
                'pages_num' => 146,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-04-23 00:00:00',
                'description' => 'description text',
                'author_name' => 'Coolkyousinnjya',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786165612036',
                'name' => 'Miss Kobayashi Dragon Maid Volume 2',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/157539/Thumbnail/book_detail_large.gif?4',
                'price' => 81,
                'pages_num' => 146,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-06-09 00:00:00',
                'description' => 'description text',
                'author_name' => 'Coolkyousinnjya',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ],
            [
                'ISBN' => '9786165612487',
                'name' => 'Miss Kobayashi Dragon Maid Volume 3',
                'cover' => 'https://cdn-local.mebmarket.com/meb/server1/174317/Thumbnail/book_detail_large.gif?2',
                'price' => 81,
                'pages_num' => 146,
                'publisher_name' => ' Zenshu',
                'publisher_date' => '2021-11-10 00:00:00',
                'description' => 'description text',
                'author_name' => 'Coolkyousinnjya',
                'stock' => 100,
                'manga_flag' => true,
                'novel_flag' => false
            ]
            
        ];
        

        foreach ($books as $key => $value) {

            if(!DB::table('authors')->where('name',$value['author_name'])->exists())
                Author::create(['name' => $value['author_name']]);

            if(!DB::table('books')->where('name',$value['name'])->exists()){
                $value['author_id'] = DB::table('authors')->where('name',$value['author_name'])->pluck('id')[0];
                Book::create($value);
            }
            
        }
    }
}